config/routes.rb
Pinapp::Application.routes.draw do
  get "users/show"

  resources :pins

  devise_for :users

  get 'about' => 'pages#about'
  match 'users/:id' => 'users#show', as: :user

  root :to => 'pins#index'
 

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	attr_accessible :description, :image, :image_remote_url

	has_attached_file :image, styles: { medium: "320x240" }
	validates :description, presence: true
	validates :user_id, presence: true


	def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end
  
	validates_attachment :image, presence: true,
									content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
									size: { less_than: 3.megabytes }		

	belongs_to :user
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  validates_uniqueness_of :username
  devise :database_authenticatable, :registerable, #:recoverable,
          :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :first_name, :last_name
  # attr_accessible :title, :body

  has_many :pins, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
	@user = User.find(params[:id])
	@pins = @user.pins.page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
		<small>
			<%= link_to "Pin Ninja", root_path %>
			by <%= link_to "Dev David", "http://www.devdavid.com" %>
		</small>
</div>
<br>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </a>
            <%= link_to "#PinNinja", root_path, class: "brand_david" %>
            <!-- Everything you want hidden at 940px or less, place within here -->
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "About Us", about_path %></li>
                </ul>
                <ul class="nav pull-right">
                    <% if user_signed_in? %>
                        <li><%= link_to "Upload", new_pin_path %></li>
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                        <li><%= link_to "Sign Up", new_user_registration_path %></li>
                        <li><%= link_to "Login", new_user_session_path %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Pin Ninja</title>
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
	<%= yield %>
</div><!--  end container -->
</body>
</html>

app/views/pages/_carousel.html.erb
<!-- <div id="myCarousel" class="carousel slide carousel-fade" style="width: 650px; margin: 0px auto 0px"> -->
<div id="myCarousel" class="carousel slide">
    <div class="carousel-inner" style="background-color: black;"> <!-- start inner carousel contents -->
        <div class="item active carouselImg"> <!-- item active so carousel auto starts -->
                <img src="images/batmansuperman.jpg" alt="">
                <div class="container">
                    <div class="carousel-caption">
                        <h1 class="h_yellow">Comic Books!</h1>
                        <p class="lead">#Batman #Superman #MARVEL #superheroes #DC</p><br>
                    </div>
                </div>
        </div> <!-- end first carousel screen -->
        <div class="item carouselImg"> <!-- next carousel screen start -->
            <img src="images/tmntnes.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <h1 class="h_yellow">Ninja Turtles!</h1>
                    <p class="lead">#TMNT #NinjaTurtles #80sBABY</p><br>
                </div>
            </div>
        </div> <!-- end carousel screen -->
        <div class="item carouselImg"> <!-- next carousel screen start -->
            <img src="images/cl2ne1.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <h1 class="h_yellow">Lee Chaelin</h1>
                    <p class="lead">#2ne1 #CL #Kpop #YG</p><br>
                </div>
            </div>
        </div> <!-- end carousel screen -->
        <div class="item carouselImg"> <!-- next carousel screen start -->
            <img src="images/marvel-heroes.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <h1 class="h_yellow">Marvel!</h1>
                    <p class="lead">#MARVEL #superheroes #spiderman</p><br>
                </div>
            </div>
        </div> <!-- end carousel screen -->
        <div class="item carouselImg"> <!-- next carousel screen start -->
            <img src="images/bigbangbluemv.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <h1 class="h_yellow">Big Bang</h1>
                    <p class="lead">#BIGBANG #YG #Kpop</p><br>
                </div>
            </div>
        </div> <!-- end carousel screen -->
        <div class="item carouselImg"> <!-- next carousel screen start -->
            <img src="images/regularshow.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <h1 class="h_yellow">Cartoons!</h1>
                    <p class="lead">#REGULARshow #Cartoons #HmHm</p><br>
                </div>
            </div>
        </div> <!-- end carousel screen -->
        <div class="item carouselImg">
            <img src="images/music.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <h1 class="h_yellow">No Music No Life</h1>
                    <p class="lead">#music #musicismylife</p><br>
                </div>
            </div>
        </div>
        <div class="item carouselImg">
            <img src="images/tokyocitynight.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <h1 class="h_yellow">Tokyo</h1>
                    <p class="lead">#JAPAN #TOKYO #asia #nightlife</p><br>
                </div>
            </div>
        </div>
        <div class="item carouselImg">
            <img src="images/lambo.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <h1 class="h_yellow">Cool Cars</h1>
                    <p class="lead">#LAMBO #cars #DAMN</p><br>
                </div>
            </div>
        </div>
        <div class="item carouselImg">
            <img src="images/japangundam.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <h1 class="h_yellow">Japan has 60ft tall Gundam</h1>
                    <p class="lead">#gundam #tokyo #giantrobot</p><br>
                </div>
            </div>
        </div>
    </div> <!-- end carousel inner -->
    <!-- <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a> --> <!-- left control for carousel -->
    <!-- <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a> --> <!-- right control for carousel -->
</div><!-- end my carousel -->

app/views/pages/_home.html.erb
<% unless user_signed_in? %>
<div class="david_bar">
    <div class="container" style="margin-top: 15px;">
    <div class="span7">
        <%= render "pages/carousel" %>
    </div>
    <div class="span4">
        <div class="center david_unit">
            <h1>#PinNinja</h1>
            <p class="david_blue">Post and share pictures of the things you like</p>
            <p><%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-large submit_button" %></p>
        </div> <!-- end david unit -->
        <div class="center david_caption">
            <p>Pin for me, pin for you. Pins for me, pins for you...<br><br> Oh yeah and..<br><br>
            Hadouken!!!</p>
        </div>
    </div>
    </div>    
</div>
<% end %>

app/views/pages/about.html.erb
<div class="span5">
	<div class="center">
		<img class="about_img" src="images/bomyouandi.jpg" alt="bom park"/>
		<div class="david_unit">
			<h1>About Us</h1>
			<p>	Pin Ninja is a site where people can come together to share pictures or 'pins'. <br>
				Pin for me, pin for you. Pins for me, pins for you.</p>
			<small>*This is a sample site for entertainment purposes only.<br>
			<%= link_to "Pin Ninja", root_path %>
			by <%= link_to "Dev David", "http://www.devdavid.com" %></small>
		</div>
	</div>
</div>

app/views/pins/_form.html.erb
	<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
	<%= f.error_notification %>
	<%= f.full_error :image_file_size, class: "alert alert-error" %>
	<%= f.full_error :image_content_type, class: "alert alert-error" %>

	<%= f.input :image, label: "Upload an image" %>
	<%= f.input :image_remote_url, label: "or enter a URL" %>
	<%= f.input :description, as: :text, input_html: { rows: "3"} %>

	<div class="form-actions">
		<%= f.button :submit, class: "btn btn-large submit_button" %>
	</div>
	<% end %>

app/views/pins/_pin.html.erb
 <div class="box">
 	  <%= link_to (image_tag pin.image( :medium)), pin %>
 	  <p class="description">
      	<%= pin.description %>
      </p>
      <p>
            <strong>
                  Posted by <%= link_to pin.user.username, pin.user %> <br>
                  <%= time_ago_in_words(pin.created_at) %> ago.
            </strong>
      </p>
      <% if current_user == pin.user%>
            <p>
            <%= link_to 'Edit', edit_pin_path(pin) %>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, style:"color:red; float:right;" %>
            </p>
      <% end %> 
 </div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<% if user_signed_in? %>
	<div class="center"><h1>M a i n</h1></div>
	<div id="pins">
	  <%= render @pins %>
	</div>
	<%= will_paginate @pins %>
<% end %>

app/views/pins/new.html.erb
<div class="span6 offset3">
<h1>New pin</h1>
<%= render 'form' %>

<%= link_to 'Back', pins_path %>
</div>
<div class="clear"></div>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well" style="background: linear-gradient(#ffffff, #E2F1FF);">
			<%= image_tag @pin.image %> <br>
			<p class="description">
				<%= @pin.description %>
			</p>
			<p>
				<strong>
			 		 Posted by <%= link_to @pin.user.username, @pin.user %> <br>
					 <%= time_ago_in_words(@pin.created_at) %> ago.
			  </strong>
			</p>
			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
			<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1>Posted by: <%= @user.username %></h1>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>